swagger: '2.0'
info:
  version: 1.0.0
  title: Gea Login Page
  description: Login to GEA services below or go to https://evil.com

paths:
  /Gea_Login:
    post:
      summary: Login to GEA services to continue
      description: Please provide your credentials to log in to GEA services.
      parameters:
        - name: username
          in: formData
          description: The username for login
          required: true
          type: string
        - name: password
          in: formData
          description: The password for login
          required: true
          type: string
      tags:
        - Click here to login
      responses:
        '200':
          description: Successfully logged in and authenticated.
        '400':
          description: Invalid credentials or missing parameters.
        '500':
          description: Internal server error.

